name: PHP CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.2'
              extensions: mbstring, intl, pdo, pdo_mysql
              coverage: none

          - name: Install dependencies
            run: |
              if [ -f composer.json ]; then
                composer install --prefer-dist --no-progress --no-suggest
              fi

          - name: Run tests
            run: |
              if [ -f vendor/bin/phpunit ]; then
                vendor/bin/phpunit
              elif [ -f phpunit.xml ] || [ -f phpunit.xml.dist ]; then
                phpunit
              else
                echo "No tests found."
              fi